### ISSUE TITLE
Design of Update command

### ISSUE THREAD

**Issue by yang-er** [IKende/BeetleX.EFCore.Extension#1]
I think the design of batch update extension in your wechat post is not good.

```csharp
var cmd = db.Customers.Update(c => c.Region == "uk")
    .Where(c => c.Country == "UK").Execute();
```

Maybe you can consider the usage of `Expression<Func<T, T>>`, which is more proper to express the update.

```csharp
var cmd = db.Customers
    .Where(c => c.Country == "UK")
    .Update(c => new Customer { Region = "uk" });
```

I think the semantics of this way is much better.

**Comment by beetlex-io** [comment]
That's a good idea!
